"""added creation date

Revision ID: 1e010bd598d8
Revises: bebb06f4a04d
Create Date: 2025-02-14 17:14:58.710924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e010bd598d8'
down_revision: Union[str, None] = 'bebb06f4a04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_id', table_name='todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    # ### end Alembic commands ###
